### ISSUE TITLE
Same image being chosen to replace adds

### ISSUE THREAD

**Issue by Ktrcoyote** [coreytegeler/add-art-chrome#20]
Hi. I've being trying to find a way to get an ad blocking application to replace all the ads with subliminal messages from the movie They Live. (OBEY. CONSUME. MONEY IS YOUR GOD. ETC.) Add Srt seems to be the best option but I'm having a lot of issues getting them to work right.  Here's a test essay I made: http://add-art.org/essays/?essay=2f77626348ec7e83a2281758e7a0bc48

Right now it seems to want to just stick with a single image, "Consume" on every site I try. Also is there a way to get it to choose ads based on dimensions? It's just cropping the rectangle ads into banner ads.

**Comment by owise1** [comment]
Hi. Right now the extension chooses the next image for each new url.  If you keep refreshing the same page it'll keep showing you the same image. But if you go to a different page it *should* choose the next one.  I'm seeing that behavior with your exhibition.

Unfortunately there isn't a way to control the dimensions of the image. It just makes sure they cover the entire ad space and if they're too big it randomly positions them.

One thing I did notice was that imugr.com was blocking the images on sites that used ssl. For example [the New York Times](https://www.nytimes.com/). you might want to do you image urls like this:

`//i.imgur.com/P8CKQEh.jpg`

instead of this:

`http://i.imgur.com/P8CKQEh.jpg`

so they'll work on more sites.

**Comment by slambert** [comment]
@owise1 We should probably include something like this in the instructions, right?

**Comment by owise1** [comment]
[added](https://add-art.org/essays/)
